### ISSUE TITLE
Can't see the environment variables when in light mode 

### ISSUE THREAD

**Issue by coffeefrappe** [hoppscotch/docs#103]
![image](https://user-images.githubusercontent.com/96076476/215348150-c63707b5-9599-49ae-b129-8b5028cebfd7.png)

**Comment by liyasthomas** [comment]
I've patched this issue in a recent commit: https://github.com/hoppscotch/hoppscotch/commit/b95e2b365a330709609e362d73ee9dc86e3fd149.

Kindly hard refresh the app to take effect the recent changes. Do let me know if this issue isn' solved.
