### ISSUE TITLE
Need to Change Twitter old logo with New x Logo in docs header and footer

### ISSUE THREAD

**Issue by varghesejose2020** [hoppscotch/docs#134]
![Screenshot_2023_0820_173609](https://github.com/hoppscotch/docs/assets/71702982/15e958f0-a4ca-42e7-a854-6b3f8190f1ad)
![Screenshot_2023_0820_173833](https://github.com/hoppscotch/docs/assets/71702982/3b9b6579-2840-49b8-ac4e-896f81f0f275)

**Comment by varghesejose2020** [comment]
still showing old logo 
![Screenshot from 2025-01-04 15-52-04](https://github.com/user-attachments/assets/eb53987a-af86-4220-bcfb-d6c8c740aad8)
@SanskritiHarmukh

**Comment by SanskritiHarmukh** [comment]
Oh, I changed it back then. I guess when we reverted certain commits some time ago, this change was also reverted. I'll look into it.
