### ISSUE TITLE
Is there a default PostgreSQL DB included in the container?

### ISSUE THREAD

**Issue by annleefores** [hoppscotch/docs#149]
In this line from  [2.install-and-build.md](https://github.com/hoppscotch/docs/blob/main/content/1.documentation/5.self-host/1.community-edition/2.install-and-build.md) 
> DATABASE_URL: This is where you add your Postgres database URL, you can also use our default database shipped within the docker container postgresql://postgres:testpass@hoppscotch-db:5432/hoppscotch

It mentions the existence of a default PostgreSQL database within the container. Is this correct, or was it actually meant to be **within the Docker Compose**?

There is some confusion regarding this matter, as discussed in https://github.com/hoppscotch/hoppscotch/issues/3414#issue-1925574550

**Comment by liyasthomas** [comment]
PostgreSQL DB is not included as part of the official images hosted on [Docker Hub](https://hub.docker.com/u/hoppscotch). Apologies for not making it clear in the documentation whether a PostgreSQL DB is included in the containers or not.

Thanks for reporting the inconsistency in the documentation. We've patched the [Install and Build](https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build) guide to reflect the changes.
