### ISSUE TITLE
Weird light mode dark mode monitor icon

### ISSUE THREAD

**Issue by Xyndra** [hoppscotch/docs#171]
I assume that this means to use preferred system but that is weird because usually you just have light and dark and it only defaults to system default. If you want to switch through it you are not interested in the system default.

**Comment by liyasthomas** [comment]
We've fixed the issue and deployed our [brand-new documentation site](https://docs.hoppscotch.io/). Let me know what you think of it and as always, share your feedback.

**Comment by Xyndra** [comment]
I think it looks very good, at least visually, but the link buttons and content buttons should perhaps be seperated
