### ISSUE TITLE
Documentation for desktop is not generated properly

### ISSUE THREAD

**Issue by daisy1754** [hoppscotch/docs#172]
Hello, I noticed this issue while browsing doc site so wanted to report here.

doc: https://docs.hoppscotch.io/documentation/clients/desktop#download-hoppscotch-desktop-app
source: https://github.com/hoppscotch/docs/blob/main/content/1.documentation/2.clients/1.desktop.md

While in mark down it mentions instruction for installation, for some reason it's not generated

<img width="1430" alt="Screenshot 2024-01-06 at 5 14 21 AM" src="https://github.com/hoppscotch/docs/assets/980077/cf8dbb6f-7fcd-4b17-a7c2-71006477087a">
<img width="1358" alt="Screenshot 2024-01-06 at 5 14 33 AM" src="https://github.com/hoppscotch/docs/assets/980077/44ae469b-6465-4f27-beed-9e27158a5573">

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. We've been facing issues with the framework we're using for documentation.

We've fixed the issue and deployed our [brand-new documentation site](https://docs.hoppscotch.io). Let me know what you think of it and as always, share your feedback.
