### ISSUE TITLE
unclear what "javaScript" to use

### ISSUE THREAD

**Issue by LeonieLionheard** [hoppscotch/docs#176]
Path: /documentation/features/scripts

Current text: "Hoppscotch provides JavaScript APIs that can be used in writing pre-request scripts and building tests. You can enter your JavaScript code and run the necessary scripts."

Problem: there are a bazillion JavaScript languages. This needs to be clarified. For example use the standardized version called ECMA-Script.

**Comment by liyasthomas** [comment]
Nice catch. I'll change that to [ECMAScript](https://tc39.es/ecma262).

**Comment by liyasthomas** [comment]
Changes are live hence closing this ticket.
