### ISSUE TITLE
Issue on docs - Broken link

### ISSUE THREAD

**Issue by FonsSalesupply** [hoppscotch/docs#191]
The link in "Select the [Grant Type](/documentation/features/oauth2) from Authorization Code (with or without PKCE), Client Credentials, Password Credentials, and Implicit" redirects to `/documentation/getting-started/introduction`.

It looks like the link should refer to `#grant-types`, locally editing this through the inspector doesn't fix the issue.

**Comment by SanskritiHarmukh** [comment]
Thank you for noticing. Issue Fixed ✅

**Comment by SanskritiHarmukh** [comment]
Thank you for noticing. Issue Fixed ✅
