### ISSUE TITLE
Add a page that describes the "context-aware menu"

### ISSUE THREAD

**Issue by SanskritiHarmukh** [hoppscotch/docs#205]
## Overview:
Context-aware menus help you quickly execute actions by selecting a piece of text and elements. Context Menus on text elements help you create variables, add query parameters to the parameters tab, and even open a new request tab when a URL is selected.

## What You Need to Do:
Add a page under `/documentation/features` named `"Context Menu"` and describe in detail the behavior of the Context Menu, including a **brief** and **how/when** to use all three types of menus that are suggested when you hover over selected text.

## Resource:
- Open the documentation in Dev mode by following the instructions in the [README file](https://github.com/hoppscotch/docs/blob/main/README.md).
- You can use various Mintlify components in the page. Learn how to use them through their [documentation](https://mintlify.com/docs/quickstart).
- Learn more about the Context Menu from this [blog](https://dev.to/hoppscotch/introducing-hoppscotch-enterprise-edition-and-a-plethora-of-features-the-hoppscotch-august-2023-release-you-cant-miss-hcg) and [video](https://www.linkedin.com/feed/update/urn:li:activity:7193540377113509890).

**Comment by ganeshpatil386386** [comment]
Hey Sanskriti, 

I want to work on this issue can you assign it to me?

**Comment by SanskritiHarmukh** [comment]
Hi @ganeshpatil386386 , before assigning the issue, I'd love to know if you've registered for the TestMu Conference?

**Comment by ganeshpatil386386** [comment]
Yes. I registered.

**Comment by SanskritiHarmukh** [comment]
Cool. Assigning you the issue.
