### ISSUE TITLE
There is no link to download the repo in the docs.

### ISSUE THREAD

**Issue by gtlsgamr** [hoppscotch/docs#207]
Path: /documentation/self-host/community-edition/getting-started

There is no link to download the repo in the docs.

**Comment by SanskritiHarmukh** [comment]
Added the link of repository in [Install and Build](https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build) page, masked for "cloned repository" and also, in [getting started](https://docs.hoppscotch.io/documentation/self-host/getting-started) page.
