### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by donfreddy** [hoppscotch/docs#21]
Hello !

I have started the translation of the document in French so if someone also wishes to participate thank you to let me know so that I add you as a collaborator in my fort
here is the link: https://github.com/Donfreddy/docs

**Comment by thomasbnt** [comment]
> hi @thomasbnt ! thanks for your help I just pushed my last translations so now you can pull and work on the content/fr/quickstart/{script, socket, sse, tests, websokek}.md files

Goood!

**Comment by thomasbnt** [comment]
Hello again @Donfreddy,
Pushed to the https://github.com/Donfreddy/docs/tree/french_translation

c8bb63169729d54c6f7b87d6dbad936b6de56e13 2de8697f0133fcbeb4aeb9a4965bd69051c17105 101b5232bae20d95121fe5c21e5c4a0d4ae52fc9 f3accdac1de71e7b4facab98f191bdf1a3b888d6 4f482e50bfd8a3f66d39c7d4c3df60c96a9f65b8


And edited small error typo on `github` ➡️  `GitHub` at e984e5b3dd4d6eef31378ea7dbb6e2d7d038ed4c

**Comment by Donfreddy** [comment]
Thank you @thomasbnt 
I created a pull request
there remains the french version of screenshots
