### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by tommihietanen** [hoppscotch/docs#240]
Path: /documentation/getting-started/rest/pre-request-scripts
---
You can use the pre-request script for a pre-processing task such as:

Setting parameters, headers.
Adding body data.
Adding variable values.
Including timestamps in request headers.
---
Example for setting headers from envs via pre-request script is needed.
There is no access to request in the pre-request scripts.

**Comment by liyasthomas** [comment]
Hi @tommihietanen, you can use environment variables in the Headers tab as usual and
before executing a request, you can use pre-request scripts to set its values at run-time.

<img width="1078" alt="Screenshot 2024-09-04 at 8 04 14 PM" src="https://github.com/user-attachments/assets/d6dd044b-6b1c-4bec-a23f-5bedd1c785aa">

<img width="1078" alt="Screenshot 2024-09-04 at 8 04 24 PM" src="https://github.com/user-attachments/assets/d90c737c-b067-42f5-8c21-fc4a321412f5">
