### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by ayushipatel007** [hoppscotch/docs#250]
Path: /documentation/features/interceptor 
Hello, this is Ayushi
I started using hoppscotch from last few months. As I wanted to use it for localhost it needed browser extension and I download it as per docs.hoppscotch.io. But the issue is even after having browser extension it is not working for localhost requests. I had write the code correctly and had started the server in terminal. 
I tried to look for the solution but I wasn't able to find anything that's why I am writing this issue here. 
![Git-bash Terminal   VS Code](https://github.com/user-attachments/assets/4b39d0bf-124d-4aa9-832c-7754cf43b3cf)
![Hoppscotch](https://github.com/user-attachments/assets/8faca000-9aea-423f-9999-a8fe40891fa5)

**Comment by SanskritiHarmukh** [comment]
Hi @ayushipatel007, have you added the Base URL under origins in the browser extension?

**Comment by ayushipatel007** [comment]
Yes, I had

**Comment by SanskritiHarmukh** [comment]
Okay, could you please confirm if your server is set up to handle **HTTPS** requests, or should the URL be using **HTTP** instead? If the server isn't configured for HTTPS, try changing the URL to `http://localhost:8080` and see if that resolves the issue.

**Comment by ayushipatel007** [comment]
I will try that.

**Comment by ayushipatel007** [comment]
I had changed my link, and it worked. Thank you!!
