### ISSUE TITLE
To make Environment dropdown always visible

### ISSUE THREAD

**Issue by altrusl** [hoppscotch/docs#43]
Currently, to switch environments, the user needs to navigate from the Collections section to the Environments section, select the desired environment and return to Collections.
If the user works with 2-3 API requests and several environments that's quite a lot of extra clicks

Also in the Collection view user does not see current environment and needs to switch to the Environments section to check it

I think it would be more convenient if the environment selector was always visible - it does not take up much space and is logically part of the workspace.

**Comment by liyasthomas** [comment]
Thank you for this feature request. We'll look into implement this.

**Comment by altrusl** [comment]
Glad to help
Just moved flawlessly big API collection from Postman and i am very happy with the UI/UX and performance 
The only issue was migration of environments
I have many of them - local, dev, staging, prod / for API and service providers -  that's just for one collection, and had to import them one by one
Thanks for this app, it is very little-known and underestimated.

**Comment by liyasthomas** [comment]
Hi @altrusl, here's a sneak peek of the all-new revamped Collection importer that we're working on:

<img width="1440" alt="Screenshot 2022-01-12 at 11 40 11 AM" src="https://user-images.githubusercontent.com/10395817/149073496-ef7d300b-f1ab-4d43-b5d5-a79368e77f72.png">


We'll be working on the bulk environment importer with support to import Postman environments as well in the next cycle. Follow the project on GitHub for the product updates.

**Comment by liyasthomas** [comment]
This feature is implemented in the latest release, hence closing.
