### ISSUE TITLE
Set environment variable

### ISSUE THREAD

**Issue by mikheillomidze** [hoppscotch/docs#46]
How can I set the environment variable in the tests script?
I was used to setting variables in postman like this:
```
var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("TOKEN", jsonData.AuthenticationResult.IdToken);
```

Can I do something similar in hopscotch?

**Comment by rcdmk** [comment]
Sadly, it seems to only be available in pre-request scripts:

```js
pw.env.set("variable_name", "value");
```

**Comment by kahennig** [comment]
Hi @mikheillomidze, yes, this was discussed here: [#1425](https://github.com/hoppscotch/hoppscotch/issues/1425).
I am also eager to have this features. It's the last issue keeping me from migrating.

**Comment by mrteey** [comment]
I have found a way: 
// Set an environment variable
pw.env.set("token", pw.response.body.token);

**Comment by lapo-luchini** [comment]
> I have found a way

Yes! Seems to be available in the most recent release, it wasn't working like this a few days ago.

**Comment by liyasthomas** [comment]
Hoppscotch now allows setting environment variables from Test scripts, hence closing.
Doc: https://docs.hoppscotch.io/quickstart/tests#envsetvariablevalue

**Comment by kahennig** [comment]
Thank you!!!

**Comment by kerembeyazit** [comment]
Cannot find a variable called `pw.response`.

<img width="343" alt="Image" src="https://github.com/user-attachments/assets/7339024d-42bb-4eaa-88ec-d794e56f60d3" />

**Comment by Layhout-WB** [comment]
> Cannot find a variable called `pw.response`.
> 
> <img alt="Image" width="343" src="https://private-user-images.githubusercontent.com/3125515/440705621-7339024d-42bb-4eaa-88ec-d794e56f60d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAzMDc3NjcsIm5iZiI6MTc1MDMwNzQ2NywicGF0aCI6Ii8zMTI1NTE1LzQ0MDcwNTYyMS03MzM5MDI0ZC00MmJiLTRlYWEtODhlYy1kNzk0ZTU2ZjYwZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA2MTlUMDQzMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhlNzM0NzUyMzQwYTNhMmNiOTg4MGNkM2FlYTBlZTVmMmVkOTc3MDI2YWFjZmZkZjJjYjc3YzNlYzFkZGNjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5ZFg20xEAPFijx8QIhyRdowtjy5W5C3A1x4QaCD0hvQ">

**Comment by Layhout** [comment]
> Cannot find a variable called `pw.response`.
> 
> <img alt="Image" width="343" src="https://private-user-images.githubusercontent.com/3125515/440705621-7339024d-42bb-4eaa-88ec-d794e56f60d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAzMDc4MzIsIm5iZiI6MTc1MDMwNzUzMiwicGF0aCI6Ii8zMTI1NTE1LzQ0MDcwNTYyMS03MzM5MDI0ZC00MmJiLTRlYWEtODhlYy1kNzk0ZTU2ZjYwZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA2MTlUMDQzMjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YwZjVhM2QyZDVmMTAxNTkyZjJhY2M5YzRkYTk3YjlmMDZmOTlhOGFkMjRiN2Q4NTFkNThlZjJhMjhlZDNkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2igYysSVDH8UrfabtCr-61LiRF71efwAdiNHGw6ic5Q">

try it in test tab
