### ISSUE TITLE
Spelling Mistake in docs.

### ISSUE THREAD

**Issue by glaucusec** [hoppscotch/docs#48]
- First sentence in the `https://docs.hoppscotch.io/features/authorization` - "REST_ APIs use authorizatiom to ensure that a client has secure access only to the resources permitted by their roles. "
- `authorizatiom` is in wrong spelling.

**Comment by liyasthomas** [comment]
Fixed in https://github.com/hoppscotch/docs/commit/2dea97da9efe140394627e5f356d223c69d0fd11
