### ISSUE TITLE
Throws 404 code when visiting any route directly

### ISSUE THREAD

**Issue by ml4den** [hoppscotch/docs#60]
### Description
When browsing the docs website a 404 error is returned if the entry point is anything apart from https://docs.hoppscotch.io/.

Scenario A:

1. Visit https://docs.hoppscotch.io/, browser loads the page.
2. Get code 200.
3. Click GraphQL (or anything else), Nuxt changes the route and renders the page.
4. Code is still 200.

Scenario B:

1. Visit https://docs.hoppscotch.io/graphql (or any other direct route), browser loads the page.
2. Get code 404.
3. Click Introduction (or anything else), Nuxt changes the route and renders the page.
4. Code is still 404.

### Impact
⚠️ This will be hurting docs SEO quite badly, making it more difficult for people to find info on the project.

### Cause

Here are some [relevant](https://stackoverflow.com/questions/56673290/nuxt-application-returns-404-when-dynamic-routes-are-refreshed-tomcat-server) [results](https://stackoverflow.com/questions/47388603/nuxt-js-refresh-url-get-404-not-found).

**Comment by rahuldimri** [comment]
Its look good to me when I visited the above page. I tried with both the option. Can you please confirm.?

**Comment by ml4den** [comment]
Scenario B still returns a 404 status code, even though it loads the page correctly.
![image](https://user-images.githubusercontent.com/6958626/192856636-3ef1b530-1ace-43c5-801c-a789e17bcc7c.png)

**Comment by Piperapk** [comment]
Can confirm, 404 when accessing any route directly that isn't the docs homepage.

**Comment by liyasthomas** [comment]
This should be fixed with the latest release on https://docs.hoppscotch.io.
